<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190917/1-1Z91G41950.jpg ",93,234);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190917/1-1Z91G41950.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="80";
$z[1][4]['height']="80";
$z[2]=Array("img"," /uploads/allimg/190917/1-1Z91G41950-50.jpg ",236,385);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190917/1-1Z91G41950-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="410";
$z[2][4]['height']="283";
$z[3]=Array("img"," /uploads/allimg/190917/1-1Z91G41950-51.jpg ",387,536);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190917/1-1Z91G41950-51.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="220";
$z[3][4]['height']="150";

?>