<?php
$z[0]=Array("field","",194,217);
$z[0][4]=array();
$z[0][4]['name']="id";
$z[1]=Array("field","",231,260);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n					<li class=\"am-g\"> <a href=\"/m[field:arcurl/]\" class=\"am-list-item-hd\">[field:title /]</a>\r\n					</li>",346,505);
$z[2][4]=array();
$z[2][4]['titlelen']="60";
$z[2][4]['row']="8";
$z[3]=Array("field","",653,676);
$z[3][4]=array();
$z[3][4]['name']="id";

?>