
  <m:item name='更新设置' link='makehtml_m/makehtml_config.php' rank='10' target='main' />
  <m:item name='更新主页HTML' link='makehtml_m/makehtml_index.php' rank='10' target='main' />
  <m:item name='更新栏目HTML' link='makehtml_m/makehtml_list.php' rank='10' target='main' />
  <m:item name='更新文档HTML' link='makehtml_m/makehtml_archives.php' rank='10' target='main' />
  <m:item name='一键更新手机网站' link='makehtml_m/makehtml_all.php' rank='10' target='main' />
