<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/190424/1-1Z4241AG6.jpg ",93,248);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190424/1-1Z4241AG6-lp.jpg";
$z[1][4]['text']="包装仓储";
$z[1][4]['width']="135";
$z[1][4]['height']="89";

?>