<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/190424/1-1Z4241FP4.jpg ",93,234);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190424/1-1Z4241FP4.jpg";
$z[1][4]['text']="城西";
$z[1][4]['width']="";
$z[1][4]['height']="";
$z[2]=Array("img"," /uploads/allimg/190424/1-1Z4241FP4-50.jpg ",236,383);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190424/1-1Z4241FP4-50.jpg";
$z[2][4]['text']="佣兵";
$z[2][4]['width']="";
$z[2][4]['height']="";

?>