
-----------------------------------------------
<m:top name='模块管理' c='6,' display='block'>
    <m:item name='模块管理' link='module_main.php' rank='sys_module' target='main' />
    <m:item name='上传新模块' link='module_upload.php' rank='sys_module' target='main' />
    <m:item name='模块生成向导' link='module_make.php' rank='sys_module' target='main' />
    </m:top>
<m:top item='7' name='辅助插件' display='block'>
  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />
  <m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />
<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />
<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />

</m:top>

<m:top item='7' name='手机静态页生成' display='block'>
  <m:item name='更新设置' link='makehtml_m/makehtml_config.php' rank='10' target='main' />
  <m:item name='更新主页HTML' link='makehtml_m/makehtml_index.php' rank='10' target='main' />
  <m:item name='更新栏目HTML' link='makehtml_m/makehtml_list.php' rank='10' target='main' />
  <m:item name='更新文档HTML' link='makehtml_m/makehtml_archives.php' rank='10' target='main' />
  <m:item name='一键更新手机网站' link='makehtml_m/makehtml_all.php' rank='10' target='main' />
</m:top>



-----------------------------------------------
