<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190725/1-1ZH5141154.jpg ",93,197);
$z[1][4]=array();
$z[1][4]['ddimg']="";
$z[1][4]['text']="";
$z[1][4]['width']="164";
$z[1][4]['height']="220";
$z[2]=Array("img"," /uploads/allimg/190725/1-1ZH5141154-50.jpg ",199,342);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190725/1-1ZH5141154-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="";
$z[2][4]['height']="";
$z[3]=Array("img"," /uploads/allimg/190725/1-1ZH5141154-51.jpg ",344,487);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190725/1-1ZH5141154-51.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="";
$z[3][4]['height']="";

?>