<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190424/1-1Z424164956.jpg ",93,250);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190424/1-1Z424164956.jpg";
$z[1][4]['text']="吴京肌肉";
$z[1][4]['width']="255";
$z[1][4]['height']="140";
$z[2]=Array("img"," /uploads/allimg/190424/1-1Z424164956-50.jpg ",252,415);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190424/1-1Z424164956-50.jpg";
$z[2][4]['text']="吴京打伞";
$z[2][4]['width']="210";
$z[2][4]['height']="140";
$z[3]=Array("img"," /uploads/allimg/190424/1-1Z424164956-51.jpg ",417,580);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190424/1-1Z424164956-51.jpg";
$z[3][4]['text']="吴京映照";
$z[3][4]['width']="180";
$z[3][4]['height']="101";
$z[4]=Array("img"," /uploads/allimg/190424/1-1Z424164956-52.jpg ",582,742);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/190424/1-1Z424164956-52.jpg";
$z[4][4]['text']="小美女";
$z[4][4]['width']="200";
$z[4][4]['height']="150";

?>